[workspace]
members = [
    "client-programs/*",
    "crates/*",
    "native-host",
    "zkvm-host",
    "prover-server",
]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
authors = ["zachobront"]
homepage = ""
repository = ""

[workspace.dependencies]

# kona
kona-common = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-common-proc = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-preimage = { git = "https://github.com/ethereum-optimism/kona", branch = "main", features = [
    "rkyv",
] }
kona-primitives = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-mpt = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-derive = { git = "https://github.com/ethereum-optimism/kona", branch = "main", default-features = false }
kona-executor = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-client = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }
kona-host = { git = "https://github.com/ethereum-optimism/kona", branch = "main" }

# general
anyhow = { version = "1.0.86", default-features = false }
cfg-if = "1.0.0"
spin = { version = "0.9.8", features = ["mutex"] }
lru = "0.12.3"
async-trait = "0.1.80"
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
clap = "4.5.9"
cargo_metadata = "0.18.1"
dotenv = "0.15.0"
num-format = "0.4.4"
futures = "0.3.30"
serde_cbor = "0.11.2"
log = "0.4.22"
itertools = "0.13.0"


# serialization
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.117", default-features = false }
rkyv = "0.7.44"
hex = "0.4.3"

# local
client-utils = { path = "crates/client-utils" }
host-utils = { path = "crates/host-utils" }
zkvm-host = { path = "zkvm-host" }
prover-server = { path = "prover-server" }

# ethereum
alloy = { version = "0.2", default-features = false, features = ["full"] }
alloy-primitives = { version = "0.7.6", default-features = false }
alloy-rlp = { version = "0.3.5", default-features = false }
alloy-eips = { version = "0.2", default-features = false }
revm = { git = "https://github.com/bluealloy/revm", version = "13.0", default-features = false }
bincode = "1.3.3"
base64 = "0.22.1"
tower-http = { version = "0.5.2", features = ["limit"] }
alloy-consensus = { version = "0.2", default-features = false }
alloy-sol-types = { version = "0.7.6" }
op-alloy-consensus = { version = "0.1.4", default-features = false }

# sp1
sp1-lib = { git = "https://github.com/succinctlabs/sp1.git", branch = "experimental", features = [
    "verify",
] }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "experimental", features = [
    "verify",
] }
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", branch = "experimental" }
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", branch = "experimental" }

# kzg
kzg-rs = { git = "https://github.com/leruaa/kzg-rs", branch = "verify_blobs", features = [
    "cache",
] }


# sp1
[profile.release-client-lto]
inherits = "release"
panic = "abort"
codegen-units = 1
lto = "fat"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", branch = "patch-v0.10.8", package = "sha2" }
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", branch = "patch-ecdsa-v0.16.9" }
# TODO: Remove this once we switch off of kzg-rs.
bls12_381 = { git = "https://github.com/leruaa/bls12_381", branch = "msm_variable_base" }
bn = { git = "https://github.com/0xWOLAND/bn.git", package = "substrate-bn", default-features = false }
