[package]
name = "op-succinct-prove"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "single"
path = "bin/single.rs"

[[bin]]
name = "multi"
path = "bin/multi.rs"

[[bin]]
name = "agg"
path = "bin/agg.rs"

[[bin]]
name = "fetch_and_save_proof"
path = "bin/fetch_and_save_proof.rs"

[[bin]]
name = "vkey"
path = "bin/vkey.rs"

[[bin]]
name = "cost_estimator"
path = "bin/cost_estimator.rs"

[dependencies]

# workspace
alloy-primitives = { workspace = true }
alloy = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
cargo_metadata = { workspace = true }

# kona
kona-host = { workspace = true }
kona-primitives.workspace = true

# local
op-succinct-host-utils.workspace = true
op-succinct-client-utils.workspace = true

# sp1
sp1-sdk = { workspace = true }
anyhow.workspace = true
dotenv.workspace = true
num-format.workspace = true
log.workspace = true
csv.workspace = true
serde = { workspace = true }
reqwest = { workspace = true }
rayon = "1.10.0"

[build-dependencies]
sp1-build = { workspace = true }
op-succinct-host-utils = { workspace = true }
