services:
  # OP Succinct Server
  op-succinct-server:
    build:
      context: .
      dockerfile: ./succinct/Dockerfile
    env_file:
      - .env.server
    restart: unless-stopped
    ports:
      - "3000:3000"

  # OP Succinct Proposer
  op-succinct-proposer:
    build:
      context: .
      dockerfile: ./op/Dockerfile.op_proposer
    env_file:
      - .env.server
    restart: unless-stopped
    depends_on:
      - op-succinct-server
    volumes:
      - ./db:/usr/local/bin/dbdata/
