[package]
name = "host-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true
client-utils.workspace = true
rkyv.workspace = true
kona-host.workspace = true
sp1-sdk.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true
serde_cbor.workspace = true
revm.workspace = true
dotenv.workspace = true
tokio.workspace = true
futures.workspace = true
num-format.workspace = true
serde.workspace = true
