name: OP Succinct

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_native_programs:
    runs-on:
      - runs-on
      - runner=16cpu-linux-x64
      - run-id=${{ github.run_id }} 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Compile the fault proof program
      run: cargo build --profile release-client-lto
      working-directory: programs/fault-proof
    - name: Compile the range program
      run: cargo build --profile release-client-lto
      working-directory: programs/range
  build_zkvm_programs:
    runs-on:
      - runs-on
      - runner=64cpu-linux-x64
      - run-id=${{ github.run_id }} 
    steps:
    - name: Install SP1 toolchain
      run: |
        curl -L https://sp1.succinct.xyz | bash
        ~/.sp1/bin/sp1up 
        ~/.sp1/bin/cargo-prove prove --version
    - name: Compile programs
      run: |
        cargo prove build --binary fault-proof &
        cargo prove build --binary range &
        cargo prove build --binary aggregation &
        wait
      working-directory: programs
