name: OP Succinct

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Compile the fault proof program
      run: cargo build --profile release-client-lto
      working-directory: client-programs/fault-proof
    - name: Compile the range program
      run: cargo build --profile release-client-lto
      working-directory: client-programs/range
