name: Docker Compose Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-compose-test:
    name: Docker Compose Test
    runs-on:
      - runs-on
      - runner=64cpu-linux-x64
      - run-id=${{ github.run_id }}    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose setup
        run: |
          docker compose build