name: OP Proposer [Go]

on:
  pull_request:
    branches:
      - main
    paths:
      - 'op-proposer-go/**'

jobs:
  test_op_proposer_go:
    runs-on:
      - runs-on
      - runner=16cpu-linux-x64
      - run-id=${{ github.run_id }}  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
    - name: Run main_test.go
      run: go test -v ./server/main_test.go
      working-directory: op-proposer-go
      env:
        L2_RPC: ${{ secrets.L2_RPC }}
        L2_NODE_RPC: ${{ secrets.L2_NODE_RPC }}
        L1_RPC: ${{ secrets.L1_RPC }}
        L1_BEACON_RPC: ${{ secrets.L1_BEACON_RPC }}
  docker-compose-test:
    name: Docker Compose Test
    runs-on:
      - runs-on
      - runner=64cpu-linux-x64
      - run-id=${{ github.run_id }}    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose setup
        run: |
          docker compose build
